spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pubs-routes-service
          uri: lb:http://PUBS-ROUTES-SERVICE
          predicates:
            - Path=/api/routes/**
        - id: pubs-data-service
          uri: lb:http://PUBS-DATA-SERVICE
          predicates:
            - Path=/api/pubs/**
  application:
    name: gateway-service
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
          probability: 1.0

server:
  port: 8322