spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://db-pubs:3306/pubber_pubs
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        boot:
          allow_jdbc_metadata_access: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
springdoc:
  swagger-ui:
    path: /client/
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
server:
  port: 8543