
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - basic-net
    command: --logging.level.zipkin2=DEBUG
  config:
    container_name: config
    build: ./services/config-server
    hostname: config
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      API_KEY: ${GEOAPIFY_API_KEY}
    ports:
      - "8888:8888"
    networks:
      - basic-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
  discovery:
    container_name: discovery
    build: ./services/discovery
    ports:
      - "8761:8761"
    networks:
      - basic-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config:
        condition: service_healthy
  pubs-data:
    container_name: pubs-data
    build: ./services/pubs-data-service
    ports:
      - 8543:8543
    networks:
      - basic-net
    links:
      - zipkin
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      API_KEY: ${GEOAPIFY_API_KEY}
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy

  pubs-routes:
    container_name: pubs-routes
    build: ./services/pubs-routes-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8444:8444
    networks:
      - basic-net
    links:
      - zipkin
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_healthy
  gateway:
    container_name: gateway
    build: ./services/gateway
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8322:8322
    networks:
      - basic-net
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_started
      pubs-data:
        condition: service_started
networks:
  basic-net:
    driver: bridge
